// <auto-generated />
namespace HumberAreaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_author_article_volunteer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_author_article_volunteer));
        
        string IMigrationMetadata.Id
        {
            get { return "202004100857493_added_author_article_volunteer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
