// <auto-generated />
namespace HumberAreaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updated_application : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_application));
        
        string IMigrationMetadata.Id
        {
            get { return "202004112112292_updated_application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
