// <auto-generated />
namespace HumberAreaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Appointment_Staff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointment_Staff));
        
        string IMigrationMetadata.Id
        {
            get { return "202004131924055_Appointment_Staff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
