// <auto-generated />
namespace HumberAreaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_Application : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Application));
        
        string IMigrationMetadata.Id
        {
            get { return "202004100356207_Added_Application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
